functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Должна существовать возможность смены языка.
  - Должна существовать возможность смены валюты независимо от выбора языка.
  - Список фильтров должен включать в себя специфичные категории поиска по выбранной категории товаров.
  - Описание на карточке товара должно быть на выбранном языке.
  - Должна существовать возможность увеличения изображений в карточке товара.
  - Наличие кнопки, отправляющей на просмотр отзывов в карточке товара.
  - Наличие кнопки внизу страницы, возвращающей наверх.
  - Если нет личного кабинета пользователя, то должна присутствовать форма, принимающая данные от пользователя при оформлении заказа из корзины.